// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Cv5GEdTr_wuUEqz8WfFcez079Ky-ncA',
    appId: '1:982316071462:web:b0490a3ce5e4377570c4e7',
    messagingSenderId: '982316071462',
    projectId: 'yakitasistan',
    authDomain: 'yakitasistan.firebaseapp.com',
    storageBucket: 'yakitasistan.appspot.com',
    measurementId: 'G-4CKQXYXT0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0ovzYsLMqbubwvyOISMXKn5IbxZEEtE',
    appId: '1:982316071462:android:39cd12b5ae82406a70c4e7',
    messagingSenderId: '982316071462',
    projectId: 'yakitasistan',
    storageBucket: 'yakitasistan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fmsSRWIel3MIe31L4FyuyuJ7XUJCXI0',
    appId: '1:982316071462:ios:38e231ca824ce1c570c4e7',
    messagingSenderId: '982316071462',
    projectId: 'yakitasistan',
    storageBucket: 'yakitasistan.appspot.com',
    iosBundleId: 'ebaysoft.yakitAsistan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fmsSRWIel3MIe31L4FyuyuJ7XUJCXI0',
    appId: '1:982316071462:ios:38e231ca824ce1c570c4e7',
    messagingSenderId: '982316071462',
    projectId: 'yakitasistan',
    storageBucket: 'yakitasistan.appspot.com',
    iosBundleId: 'ebaysoft.yakitAsistan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Cv5GEdTr_wuUEqz8WfFcez079Ky-ncA',
    appId: '1:982316071462:web:1323e65fc1d6773770c4e7',
    messagingSenderId: '982316071462',
    projectId: 'yakitasistan',
    authDomain: 'yakitasistan.firebaseapp.com',
    storageBucket: 'yakitasistan.appspot.com',
    measurementId: 'G-35G351SJNN',
  );
}
